const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const breed=$('#breed'),division=$('#division'),track=$('#track'),award=$('#award'),fields=$('#competitionFields');
BREEDS.forEach(b=>breed.add(new Option(b,b))); breed.value='French Bulldogs';
Object.entries(DIVISIONS).forEach(([n,s])=>division.add(new Option(`Division ${n} — ${s}`,n))); division.value='9';
$('#showDate').value=new Date().toISOString().slice(0,10);
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');renderAll()});
function setAwards(){award.innerHTML=''; const opts=track.value==='CH'?[['WD','Winners Dog'],['WB','Winners Bitch'],['BOW','Best of Winners'],['BOB','Best of Breed'],['BOS','Best of Opposite Sex']]:[['BOB','Best of Breed'],['BOS','Best of Opposite Sex'],['SD','Select Dog'],['SB','Select Bitch']];opts.forEach(x=>award.add(new Option(x[1],x[0]))); renderFields()}
function renderFields(){let a=award.value,t=track.value; if(t==='CH'&&a==='BOW')fields.innerHTML=num('dogs','Regular class dogs judged')+num('bitches','Regular class bitches judged'); else if(t==='GCH'&&['SD','SB'].includes(a)) fields.innerHTML=num('sameSex','Same-sex dogs/bitches judged'); else fields.innerHTML=num('count','Dogs counted for this award'); $('#countHint').textContent=t==='GCH'&&['SD','SB'].includes(a)?'For Select, 15PTS subtracts the BOB/BOS winner from the same-sex competition before applying the schedule.':'Enter only dogs actually judged and eligible to count for this award.';bindInputs();calc()}
function num(id,label){return `<label>${label}<input id="${id}" type="number" inputmode="numeric" min="0" value="0"></label>`}
function bindInputs(){$$('#calcForm input,#calcForm select').forEach(x=>{x.oninput=calc;x.onchange=calc})}
function schedule(){let key=`${division.value}|${breed.value}`,v=VERIFIED[key]||UNIVERSAL;return {v,verified:!!VERIFIED[key]}}
function ptsFor(count,sex,v){let offset=sex==='dog'?0:1,p=0;for(let i=1;i<=5;i++)if(count>=v[(i-1)*2+offset])p=i;return p}
function calc(){let {v,verified}=schedule(),a=award.value,t=track.value,sex=$('#sex').value,p=0,count=0;if(t==='CH'&&a==='BOW'){let d=+$(`#dogs`)?.value||0,b=+$(`#bitches`)?.value||0;p=Math.max(ptsFor(d,'dog',v),ptsFor(b,'bitch',v)); if(!p){let total=d+b;if(total>=v[sex==='dog'?0:1])p=1}count=d+b}else{count=+(($('#count')||$('#sameSex'))?.value)||0;if(t==='GCH'&&['SD','SB'].includes(a))count=Math.max(0,count-1);let sx=(a==='SD')?'dog':(a==='SB')?'bitch':sex;p=ptsFor(count,sx,v)}$('#points').textContent=p;$('#resultText').textContent=p>=3?`${p}-point major`:`${p} point${p===1?'':'s'}`;$('#scheduleStatus').textContent=verified?'Verified 2026 schedule row':'⚠ Schedule needs verification';return {p,count,verified}}
track.onchange=setAwards;award.onchange=renderFields;division.onchange=calc;breed.onchange=calc;$('#sex').onchange=calc;setAwards();
function records(){return JSON.parse(localStorage.getItem('15pts.records')||'[]')}function saveRecords(r){localStorage.setItem('15pts.records',JSON.stringify(r))}
$('#saveBtn').onclick=()=>{let c=calc();if(!$('#dogName').value.trim())return alert('Add the dog’s registered name first.');let r={id:Date.now(),dog:$('#dogName').value.trim(),reg:$('#regNo').value.trim(),sex:$('#sex').value,breed:breed.value,date:$('#showDate').value,show:$('#showName').value.trim(),judge:$('#judge').value.trim(),division:division.value,track:track.value,award:award.value,points:c.p,major:c.p>=3,count:c.count,verified:c.verified};let rs=records();rs.unshift(r);saveRecords(rs);alert(`Saved: ${r.points} point${r.points===1?'':'s'}${r.major?' — major':''}`);renderAll()};
function renderAll(){let rs=records(),ch=rs.filter(r=>r.track==='CH').reduce((s,r)=>s+r.points,0),gch=rs.filter(r=>r.track==='GCH').reduce((s,r)=>s+r.points,0),maj=rs.filter(r=>r.major).length;$('#summary').innerHTML=`<div class="stats"><div class="stat"><strong>${rs.length}</strong><span>RESULTS</span></div><div class="stat"><strong>${ch}</strong><span>CH PTS</span></div><div class="stat"><strong>${gch}</strong><span>GCH PTS</span></div><div class="stat"><strong>${maj}</strong><span>MAJORS</span></div></div>`;$('#recordList').innerHTML=rs.length?rs.map(r=>`<div class="record"><div class="recordTop"><div><b>${esc(r.dog)}</b><div class="meta">${r.date||'No date'} · ${esc(r.show||'Show not entered')}<br>${r.track} ${r.award} · Division ${r.division} · ${r.points} pts${r.verified?'':' · ⚠ unverified schedule'}</div></div><span class="pill ${r.major?'major':''}">${r.major?'MAJOR':r.points+' PT'}</span></div><button class="delete" onclick="del(${r.id})">Delete</button></div>`).join(''):'<div class="empty">No saved results yet.</div>';renderDogs(rs)}
function renderDogs(rs){let map={};rs.forEach(r=>(map[r.reg||r.dog]??=[]).push(r));$('#dogList').innerHTML=Object.values(map).length?Object.values(map).map(a=>{let d=a[0],ch=a.filter(x=>x.track==='CH').reduce((s,x)=>s+x.points,0),cm=a.filter(x=>x.track==='CH'&&x.major).length,g=a.filter(x=>x.track==='GCH').reduce((s,x)=>s+x.points,0),gm=a.filter(x=>x.track==='GCH'&&x.major).length;return `<div class="dogCard"><b>${esc(d.dog)}</b><div class="meta">${esc(d.reg||'No registration #')} · ${esc(d.breed)}</div><div class="progress"><i style="width:${Math.min(100,ch/15*100)}%"></i></div><div class="meta"><b>${ch}/15 CH points</b> · ${cm} CH major${cm===1?'':'s'}<br>${g}/25 GCH points · ${gm} GCH major${gm===1?'':'s'}</div></div>`}).join(''):'<div class="empty">Save a result to begin tracking a dog.</div>'}
window.del=id=>{if(confirm('Delete this saved result?')){saveRecords(records().filter(r=>r.id!==id));renderAll()}};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(records(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='15PTS-records.json';a.click();URL.revokeObjectURL(a.href)};
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
