const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const breed=$('#breed'),division=$('#division'),track=$('#track'),award=$('#award');
BREEDS.forEach(b=>breed.add(new Option(b,b))); breed.value='French Bulldogs';
Object.entries(DIVISIONS).forEach(([n,s])=>division.add(new Option(`Division ${n} — ${s}`,n))); division.value='9';
$('#showDate').value=new Date().toISOString().slice(0,10);
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');renderAll()});
function setAwards(){award.innerHTML='';const opts=track.value==='CH'?[['WD','Winners Dog (WD)'],['WB','Winners Bitch (WB)'],['WD_BOW','Winners Dog + Best of Winners'],['WB_BOW','Winners Bitch + Best of Winners'],['WD_BOS','Winners Dog + Best of Opposite Sex'],['WB_BOS','Winners Bitch + Best of Opposite Sex'],['WD_BOB','Winners Dog + Best of Breed'],['WB_BOB','Winners Bitch + Best of Breed']]:[['BOB','Champion — Best of Breed'],['BOS_D','Champion Dog — Best of Opposite Sex'],['BOS_B','Champion Bitch — Best of Opposite Sex'],['SD','Select Dog'],['SB','Select Bitch']];opts.forEach(x=>award.add(new Option(x[1],x[0])));renderFields()}
function n(id,label,help=''){return `<label>${label}<input id="${id}" type="number" inputmode="numeric" min="0" value="0">${help?`<span class="micro">${help}</span>`:''}</label>`}
function renderFields(){const ch=track.value==='CH';$('#entryTitle').textContent=ch?'Breed entry actually judged':'Breed entry actually judged';$('#entryFields').innerHTML=n('classDogs','Regular class dogs','Include Winners Dog; exclude absentees.')+n('classBitches','Regular class bitches','Include Winners Bitch; exclude absentees.')+n('champDogs',ch?'Champion / move-up dogs in BOB':'GCH-eligible dogs in BOB','Dogs entered or moved up to BOB competition.')+n('champBitches',ch?'Champion / move-up bitches in BOB':'GCH-eligible bitches in BOB','Bitches entered or moved up to BOB competition.');$('#nonRegularWrap').style.display=ch?'none':'block';$('#countHint').innerHTML=ch?'15PTS will calculate WD and WB separately, then apply BOW/BOS/BOB rules from the award selected. For CH BOB/BOS calculations, non-regular entries advancing to BOB are not counted.':'For GCH, eligible non-regular entries that advance to BOB may count. Enter them separately below; 15PTS applies the selected BOB/BOS/Select rule.';bindInputs();calc()}
function bindInputs(){$$('#calcForm input,#calcForm select').forEach(x=>{x.oninput=calc;x.onchange=calc})}
function schedule(){let key=`${division.value}|${breed.value}`,v=VERIFIED[key]||UNIVERSAL;return {v,verified:!!VERIFIED[key]}}
function ptsFor(count,sex,v){let offset=sex==='dog'?0:1,p=0;for(let i=1;i<=5;i++)if(count>=v[(i-1)*2+offset])p=i;return p}
const val=id=>+($('#'+id)?.value||0);
function calc(){const {v,verified}=schedule(),a=award.value,t=track.value;let d=val('classDogs'),b=val('classBitches'),cd=val('champDogs'),cb=val('champBitches'),nd=val('nonRegDogs'),nb=val('nonRegBitches');let p=0,count=0,explain='',sex='dog';const wd=ptsFor(d,'dog',v),wb=ptsFor(b,'bitch',v);if(t==='CH'){
 if(a==='WD'){p=wd;count=d;sex='dog';explain=`WD: ${d} regular class dog${d===1?'':'s'} → ${p} pt${p===1?'':'s'}.`}
 if(a==='WB'){p=wb;count=b;sex='bitch';explain=`WB: ${b} regular class bitch${b===1?'':'es'} → ${p} pt${p===1?'':'s'}.`}
 if(a==='WD_BOW'||a==='WB_BOW'){sex=a.startsWith('WD')?'dog':'bitch';let base=sex==='dog'?wd:wb,opp=sex==='dog'?wb:wd;p=Math.max(base,opp);if(!p&&d+b>=v[sex==='dog'?0:1])p=1;count=d+b;explain=`WD ${wd} pt${wd===1?'':'s'} · WB ${wb} pt${wb===1?'':'s'} → BOW receives ${p} pt${p===1?'':'s'}.`}
 if(a==='WD_BOS'||a==='WB_BOS'){sex=a.startsWith('WD')?'dog':'bitch';count=sex==='dog'?d+cd:b+cb;p=ptsFor(count,sex,v);explain=`BOS: ${sex==='dog'?d:b} regular + ${sex==='dog'?cd:cb} same-sex BOB entr${(sex==='dog'?cd:cb)===1?'y':'ies'} = ${count} counted → ${p} pt${p===1?'':'s'}.`}
 if(a==='WD_BOB'||a==='WB_BOB'){sex=a.startsWith('WD')?'dog':'bitch';count=(sex==='dog'?d:b)+cd+cb;let bob=ptsFor(count,sex,v);p=Math.max(bob,wd,wb);explain=`BOB: ${sex==='dog'?d:b} same-sex regular + ${cd+cb} BOB entries = ${count} counted → ${bob} pt${bob===1?'':'s'}; WD/WB crossover max = ${Math.max(wd,wb)} → ${p} pt${p===1?'':'s'} awarded.`}
 }else{if(a==='BOB'){sex=$('#sex').value;count=d+b+cd+cb+nd+nb;p=ptsFor(count,sex,v);explain=`GCH BOB: all ${count} eligible breed competitors counted.`}if(a==='BOS_D'||a==='BOS_B'){sex=a==='BOS_D'?'dog':'bitch';count=sex==='dog'?d+cd+nd:b+cb+nb;p=ptsFor(count,sex,v);explain=`GCH BOS: ${count} ${sex==='dog'?'dogs':'bitches'} in eligible competition counted.`}if(a==='SD'||a==='SB'){sex=a==='SD'?'dog':'bitch';let total=sex==='dog'?d+cd+nd:b+cb+nb;count=Math.max(0,total-1);p=ptsFor(count,sex,v);explain=`Select: ${total} same-sex competitors less the same-sex BOB/BOS winner = ${count} counted.`}}
 $('#points').textContent=p;$('#resultText').textContent=p>=3?`${p}-point major`:`${p} point${p===1?'':'s'}`;$('#calcExplanation').textContent=explain;$('#scheduleStatus').textContent=verified?'Verified 2026 schedule row':'⚠ Schedule needs verification';return {p,count,verified,explain,entry:{classDogs:d,classBitches:b,champDogs:cd,champBitches:cb,nonRegDogs:nd,nonRegBitches:nb}}}
track.onchange=setAwards;award.onchange=calc;division.onchange=calc;breed.onchange=calc;$('#sex').onchange=calc;setAwards();
function records(){return JSON.parse(localStorage.getItem('15pts.records')||'[]')}function saveRecords(r){localStorage.setItem('15pts.records',JSON.stringify(r))}
$('#saveBtn').onclick=()=>{let c=calc();if(!$('#dogName').value.trim())return alert('Add the dog’s registered name first.');let r={id:Date.now(),dog:$('#dogName').value.trim(),reg:$('#regNo').value.trim(),sex:$('#sex').value,breed:breed.value,date:$('#showDate').value,show:$('#showName').value.trim(),judge:$('#judge').value.trim(),division:division.value,track:track.value,award:award.value,awardLabel:award.options[award.selectedIndex].text,points:c.p,major:c.p>=3,count:c.count,entry:c.entry,explain:c.explain,verified:c.verified};let rs=records();rs.unshift(r);saveRecords(rs);alert(`Saved: ${r.points} point${r.points===1?'':'s'}${r.major?' — major':''}`);renderAll()};
function renderAll(){let rs=records(),ch=rs.filter(r=>r.track==='CH').reduce((s,r)=>s+r.points,0),gch=rs.filter(r=>r.track==='GCH').reduce((s,r)=>s+r.points,0),chm=rs.filter(r=>r.track==='CH'&&r.major).length,gcm=rs.filter(r=>r.track==='GCH'&&r.major).length;$('#summary').innerHTML=`<div class="stats"><div class="stat"><strong>${rs.length}</strong><span>RESULTS</span></div><div class="stat"><strong>${ch}</strong><span>CH PTS</span></div><div class="stat"><strong>${chm}</strong><span>CH MAJORS</span></div><div class="stat"><strong>${gch}</strong><span>GCH PTS</span></div></div>`;$('#recordList').innerHTML=rs.length?rs.map(r=>`<div class="record"><div class="recordTop"><div><b>${esc(r.dog)}</b><div class="meta">${r.date||'No date'} · ${esc(r.show||'Show not entered')}<br>${r.track} · ${esc(r.awardLabel||r.award)} · Division ${r.division} · ${r.points} pts${r.verified?'':' · ⚠ unverified schedule'}<br>${esc(r.explain||'')}</div></div><span class="pill ${r.major?'major':''}">${r.major?'MAJOR':r.points+' PT'}</span></div><button class="delete" onclick="del(${r.id})">Delete</button></div>`).join(''):'<div class="empty">No saved results yet.</div>';renderDogs(rs)}
function renderDogs(rs){let map={};rs.forEach(r=>(map[r.reg||r.dog]??=[]).push(r));$('#dogList').innerHTML=Object.values(map).length?Object.values(map).map(a=>{let d=a[0],ch=a.filter(x=>x.track==='CH').reduce((s,x)=>s+x.points,0),cm=a.filter(x=>x.track==='CH'&&x.major).length,g=a.filter(x=>x.track==='GCH').reduce((s,x)=>s+x.points,0),gm=a.filter(x=>x.track==='GCH'&&x.major).length;return `<div class="dogCard"><b>${esc(d.dog)}</b><div class="meta">${esc(d.reg||'No registration #')} · ${esc(d.breed)}</div><div class="progress"><i style="width:${Math.min(100,ch/15*100)}%"></i></div><div class="meta"><b>${ch}/15 CH points</b> · ${cm} CH major${cm===1?'':'s'}<br>${g}/25 GCH points · ${gm} GCH major${gm===1?'':'s'}</div></div>`}).join(''):'<div class="empty">Save a result to begin tracking a dog.</div>'}
window.del=id=>{if(confirm('Delete this saved result?')){saveRecords(records().filter(r=>r.id!==id));renderAll()}};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(records(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='15PTS-records.json';a.click();URL.revokeObjectURL(a.href)};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
