const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STATE_DIV={CT:1,ME:1,MA:1,NH:1,RI:1,VT:1,DE:2,NJ:2,NY:2,PA:2,DC:3,MD:3,NC:3,VA:3,WV:3,FL:4,GA:4,SC:4,IN:5,KY:5,MI:5,OH:5,CO:6,NV:6,UT:6,KS:7,OK:7,TX:7,OR:8,WA:8,AZ:9,CA:9,AK:10,HI:11,PR:12,MX:12,ID:13,MT:13,NE:13,NM:13,ND:13,SD:13,WY:13,AL:14,AR:14,LA:14,MS:14,TN:14,IL:15,IA:15,MN:15,MO:15,WI:15};
const STATE_NAMES={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',DC:'District of Columbia',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming',PR:'Puerto Rico',MX:'Mexico'};
const SUPERS=[['','Select…',''],['onofrio','Jack Onofrio Dog Shows','https://www.onofrio.com/'],['mbf','MB-F / Infodog','https://www.infodog.com/'],['baray','BaRay Event Services','https://barayevents.com/'],['foytrent','Foy Trent Dog Shows','https://foytrentdogshows.com/'],['rau','Jim Rau Dog Shows','https://www.raudogshows.com/'],['akc','AKC Event Search / Results','https://www.akc.org/sports/events/'],['other','Show Secretary / Other','']];
const breed=$('#breed'),state=$('#eventState'); BREEDS.forEach(b=>breed.add(new Option(b,b)));breed.value='French Bulldogs';
Object.keys(STATE_NAMES).sort((a,b)=>STATE_NAMES[a].localeCompare(STATE_NAMES[b])).forEach(k=>state.add(new Option(STATE_NAMES[k],k)));state.value='AZ';
SUPERS.forEach(x=>$('#superintendent').add(new Option(x[1],x[0]))); $('#showDate').value=new Date().toISOString().slice(0,10);
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');renderAll()});
function division(){return STATE_DIV[state.value]||null} function updateDivision(){let d=division();$('#divisionDisplay').value=d?`Division ${d} — ${DIVISIONS[d]}`:'Select event state';let dt=$('#showDate').value,w=$('#scheduleDateWarning');if(dt&&dt<'2026-05-12'){w.textContent='This show date predates the supported 2026 schedule effective May 12, 2026. Verify the historical point schedule before relying on this calculation.';w.classList.remove('hidden')}else w.classList.add('hidden');calc()}
function n(id,label,help=''){return `<label>${label}<input id="${id}" type="number" inputmode="numeric" min="0" value="0">${help?`<span class="micro">${help}</span>`:''}</label>`}
function isGCH(){return ['champion','grandchampion'].includes($('#status').value)}
function renderEntry(){let champ=isGCH();$('#entryFields').innerHTML=n('classDogs','Regular class dogs','Present and judged; include Winners Dog.')+n('classBitches','Regular class bitches','Present and judged; include Winners Bitch.')+n('champDogs','Champion / move-up dogs in BOB','Present and judged in BOB competition.')+n('champBitches','Champion / move-up bitches in BOB','Present and judged in BOB competition.');$('#nonRegularWrap').classList.toggle('hidden',!champ);$('#countHint').textContent=champ?'GCH calculations may include eligible non-regular entries that advance to BOB.':'CH BOB/BOS calculations do not count non-regular entries advancing to BOB.';bindCalcInputs()}
let selectedAwards=new Set(),selectedNOHS=new Set();
function awardDefs(){let sex=$('#sex').value,champ=isGCH();if(champ)return [{id:'BOB',label:'Best of Breed'},{id:'BOS',label:'Best of Opposite Sex'},{id:sex==='dog'?'SD':'SB',label:sex==='dog'?'Select Dog':'Select Bitch'},{id:'G1',label:'Group 1'},{id:'G2',label:'Group 2'},{id:'G3',label:'Group 3'},{id:'G4',label:'Group 4'},{id:'RBIS',label:'Reserve Best in Show'},{id:'BIS',label:'Best in Show'}];return [{id:sex==='dog'?'WD':'WB',label:sex==='dog'?'Winners Dog':'Winners Bitch'},{id:sex==='dog'?'RWD':'RWB',label:sex==='dog'?'Reserve Winners Dog':'Reserve Winners Bitch',terminal:true},{id:'BOW',label:'Best of Winners'},{id:'BOB',label:'Best of Breed'},{id:'BOS',label:'Best of Opposite Sex'},{id:'G1',label:'Group 1'},{id:'G2',label:'Group 2'},{id:'G3',label:'Group 3'},{id:'G4',label:'Group 4'},{id:'RBIS',label:'Reserve Best in Show'},{id:'BIS',label:'Best in Show'}]}
function renderAwards(reset=false){if(reset)selectedAwards.clear();let defs=awardDefs(),valid=new Set(defs.map(x=>x.id));selectedAwards=new Set([...selectedAwards].filter(x=>valid.has(x)));let reserve=[...selectedAwards].some(x=>x==='RWD'||x==='RWB');$('#awardStack').innerHTML=defs.filter(x=>{if(isGCH()){if(['G1','G2','G3','G4'].includes(x.id))return selectedAwards.has('BOB');if(['BIS','RBIS'].includes(x.id))return selectedAwards.has('G1');return true}if(reserve)return x.id==='RWD'||x.id==='RWB';if(['G1','G2','G3','G4'].includes(x.id))return selectedAwards.has('BOB');if(['BIS','RBIS'].includes(x.id))return selectedAwards.has('G1');return true}).map(x=>`<button type="button" class="awardChip ${x.terminal?'terminal ':''}${selectedAwards.has(x.id)?'selected':''}" data-award="${x.id}">${selectedAwards.has(x.id)?'✓ ':''}${x.label}</button>`).join('');$$('.awardChip').forEach(b=>b.onclick=()=>toggleAward(b.dataset.award));$('#awardHint').textContent=isGCH()?'Champion/GCH breed awards are mutually exclusive. BOB can advance to regular Group competition, but Group placements are recorded separately from GCH breed points.':'Winners may stack with BOW and then BOB or BOS. BOB may advance to Group 1–4; only Group 1 may advance to BIS/RBIS. Reserve Winners ends the regular advancement path.';let gp=[...selectedAwards].some(x=>['G1','G2','G3','G4'].includes(x));$('#groupCompareWrap').classList.toggle('hidden',!(gp&&!isGCH()));renderNOHS();calc()}
function toggleAward(a){let champ=isGCH(),sex=$('#sex').value,win=sex==='dog'?'WD':'WB',reserve=sex==='dog'?'RWD':'RWB';if(champ){if(['BOB','BOS','SD','SB'].includes(a)){selectedAwards=new Set([a])}else if(['G1','G2','G3','G4'].includes(a)){if(!selectedAwards.has('BOB'))return;['G1','G2','G3','G4','BIS','RBIS'].forEach(x=>selectedAwards.delete(x));selectedAwards.add(a)}else if(a==='BIS'||a==='RBIS'){if(!selectedAwards.has('BOB'))return;['G1','G2','G3','G4','BIS','RBIS'].forEach(x=>selectedAwards.delete(x));selectedAwards.add('G1');selectedAwards.add(a)}}else if(a===reserve){selectedAwards=new Set([reserve]);selectedNOHS.clear()}else{selectedAwards.delete(reserve);if(a===win){if(selectedAwards.has(win))selectedAwards.clear();else selectedAwards.add(win)}else if(a==='BOW'){selectedAwards.add(win);selectedAwards.has('BOW')?selectedAwards.delete('BOW'):selectedAwards.add('BOW')}else if(a==='BOB'||a==='BOS'){selectedAwards.add(win);if(a==='BOB'){selectedAwards.delete('BOS');selectedAwards.add('BOW')}else selectedAwards.delete('BOB');selectedAwards.has(a)?selectedAwards.delete(a):selectedAwards.add(a);if(!selectedAwards.has('BOB'))['G1','G2','G3','G4','BIS','RBIS'].forEach(x=>selectedAwards.delete(x))}else if(['G1','G2','G3','G4'].includes(a)){selectedAwards.add(win);selectedAwards.add('BOW');selectedAwards.add('BOB');['G1','G2','G3','G4'].forEach(x=>selectedAwards.delete(x));selectedAwards.add(a);if(a!=='G1'){selectedAwards.delete('BIS');selectedAwards.delete('RBIS')}}else if(a==='BIS'||a==='RBIS'){selectedAwards.add(win);selectedAwards.add('BOW');selectedAwards.add('BOB');['G1','G2','G3','G4'].forEach(x=>selectedAwards.delete(x));selectedAwards.add('G1');selectedAwards.delete(a==='BIS'?'RBIS':'BIS');selectedAwards.add(a)}}renderAwards()}
const NOHS_PTS={OHBOB:5,OHG1:30,OHG2:20,OHG3:15,OHG4:10,OHRBIS:75,OHBIS:100};
function nohsDefs(){return [{id:'OHBOB',label:'Owner-Handled Best of Breed'},{id:'OHG1',label:'OH Group 1'},{id:'OHG2',label:'OH Group 2'},{id:'OHG3',label:'OH Group 3'},{id:'OHG4',label:'OH Group 4'},{id:'OHRBIS',label:'OH Reserve Best in Show'},{id:'OHBIS',label:'OH Best in Show'}]}
function renderNOHS(){let on=$('#nohs').checked,reserve=[...selectedAwards].some(x=>x==='RWD'||x==='RWB');$('#nohsAwardsCard').classList.toggle('hidden',!on);if(!on||reserve){selectedNOHS.clear();if(on&&reserve){$('#nohsAwardStack').innerHTML='';$('#nohsPointsPreview').textContent='Reserve Winners does not advance to Best of Breed competition, so OHBOB is not available for this result.'}return}let defs=nohsDefs();$('#nohsAwardStack').innerHTML=defs.filter(x=>{if(x.id.startsWith('OHG'))return selectedNOHS.has('OHBOB');if(['OHRBIS','OHBIS'].includes(x.id))return selectedNOHS.has('OHG1');return true}).map(x=>`<button type="button" class="awardChip ${selectedNOHS.has(x.id)?'selected':''}" data-nohs="${x.id}">${selectedNOHS.has(x.id)?'✓ ':''}${x.label}</button>`).join('');$$('[data-nohs]').forEach(b=>b.onclick=()=>toggleNOHS(b.dataset.nohs));let p=[...selectedNOHS].reduce((a,x)=>a+(NOHS_PTS[x]||0),0);$('#nohsPointsPreview').textContent=selectedNOHS.size?`NOHS points recorded for this event: ${p}`:'Select OHBOB if earned; higher NOHS placements stack cumulatively.'}
function toggleNOHS(a){if(a==='OHBOB'){selectedNOHS.has(a)?selectedNOHS.clear():selectedNOHS.add(a)}else if(a.startsWith('OHG')){selectedNOHS.add('OHBOB');['OHG1','OHG2','OHG3','OHG4'].forEach(x=>selectedNOHS.delete(x));selectedNOHS.add(a);if(a!=='OHG1'){selectedNOHS.delete('OHBIS');selectedNOHS.delete('OHRBIS')}}else{selectedNOHS.add('OHBOB');['OHG1','OHG2','OHG3','OHG4'].forEach(x=>selectedNOHS.delete(x));selectedNOHS.add('OHG1');selectedNOHS.delete(a==='OHBIS'?'OHRBIS':'OHBIS');selectedNOHS.add(a)}renderNOHS()}
function schedule(){let key=`${division()}|${breed.value}`,v=VERIFIED[key]||UNIVERSAL;return {v,verified:!!VERIFIED[key]}}
function ptsFor(count,sex,v){let o=sex==='dog'?0:1,p=0;for(let i=1;i<=5;i++)if(count>=v[(i-1)*2+o])p=i;return p} const val=id=>+($('#'+id)?.value||0);
function calc(){let d=val('classDogs'),b=val('classBitches'),cd=val('champDogs'),cb=val('champBitches'),nd=val('nonRegDogs'),nb=val('nonRegBitches'),sex=$('#sex').value,champ=isGCH(),{v,verified}=schedule(),steps=[],best=0,control='';const wd=ptsFor(d,'dog',v),wb=ptsFor(b,'bitch',v),win=sex==='dog'?'WD':'WB';if(!selectedAwards.size){showResult(0,'Select an award','',verified);return resultObj(0,false,steps,'',verified,d,b,cd,cb,nd,nb)}
 if(!champ){let reserve=sex==='dog'?'RWD':'RWB';if(selectedAwards.has(reserve)){steps.push(`${reserve}: reserve award recorded — 0 CH points.`);best=0;control=reserve}else if(selectedAwards.has(win)){let p=sex==='dog'?wd:wb;steps.push(`${win}: ${sex==='dog'?d:b} regular ${sex==='dog'?'dogs':'bitches'} → ${p} pt${p===1?'':'s'}`);if(p>=best){best=p;control=win}}
 if(selectedAwards.has('BOW')){let p=Math.max(wd,wb);if(!p&&d+b>=v[sex==='dog'?0:1])p=1;steps.push(`BOW crossover: WD ${wd} / WB ${wb} → ${p} pt${p===1?'':'s'}`);if(p>best){best=p;control='BOW'}}
 if(selectedAwards.has('BOS')){let c=sex==='dog'?d+cd:b+cb,p=ptsFor(c,sex,v);steps.push(`BOS: ${sex==='dog'?d:b} regular + ${sex==='dog'?cd:cb} same-sex BOB entries = ${c} → ${p} pt${p===1?'':'s'}`);if(p>best){best=p;control='BOS'}}
 if(selectedAwards.has('BOB')){let c=(sex==='dog'?d:b)+cd+cb,p=ptsFor(c,sex,v);steps.push(`BOB: ${sex==='dog'?d:b} same-sex regular + ${cd+cb} BOB entries = ${c} → ${p} pt${p===1?'':'s'}`);if(p>best){best=p;control='BOB'}}
 }else{let a=[...selectedAwards].find(x=>['BOB','BOS','SD','SB'].includes(x));if(a==='BOB'){let c=d+b+cd+cb+nd+nb,p=ptsFor(c,sex,v);steps.push(`GCH BOB: ${c} eligible breed competitors → ${p} pt${p===1?'':'s'}`);best=p;control='BOB'}if(a==='BOS'){let c=sex==='dog'?d+cd+nd:b+cb+nb,p=ptsFor(c,sex,v);steps.push(`GCH BOS: ${c} same-sex eligible competitors → ${p} pt${p===1?'':'s'}`);best=p;control='BOS'}if(a==='SD'||a==='SB'){let total=sex==='dog'?d+cd+nd:b+cb+nb,c=Math.max(0,total-1),p=ptsFor(c,sex,v);steps.push(`${a}: ${total} same-sex competitors less 1 = ${c} counted → ${p} pt${p===1?'':'s'}`);best=p;control=a}}
 if(!champ&&[...selectedAwards].some(x=>['G1','G2','G3','G4'].includes(x))){let gp=val('groupComparePoints');steps.push(`Regular Group comparison: qualifying defeated-breed value entered as ${gp} point${gp===1?'':'s'}.`);if(gp>best){best=gp;control=[...selectedAwards].find(x=>['G1','G2','G3','G4'].includes(x))}}
 let explain=steps.join(' · ')+(control?` · Controlling award: ${control}.`:'');showResult(best,best>=3?`${best}-point major`:`${best} point${best===1?'':'s'}`,explain,verified);$('#trackText').textContent=champ?'GCH track':'CH track';return resultObj(best,best>=3,steps,control,verified,d,b,cd,cb,nd,nb)}
function resultObj(p,major,steps,control,verified,d,b,cd,cb,nd,nb){return {p,major,steps,control,verified,entry:{classDogs:d,classBitches:b,champDogs:cd,champBitches:cb,nonRegDogs:nd,nonRegBitches:nb}}}
function showResult(p,text,explain,verified){$('#points').textContent=p;$('#resultText').textContent=text;$('#calcExplanation').textContent=explain;$('#scheduleStatus').textContent=verified?'Verified 2026 schedule row':'⚠ Point-schedule row needs verification'}
function bindCalcInputs(){$$('#calcForm input,#calcForm select').forEach(x=>{if(!['sex','status','eventState','superintendent'].includes(x.id)){x.oninput=calc;x.onchange=calc}})}
$('#sex').onchange=()=>renderAwards(true);$('#status').onchange=()=>{renderEntry();renderAwards(true)};$('#nohs').onchange=()=>{if(!$('#nohs').checked)selectedNOHS.clear();renderNOHS()};state.onchange=updateDivision;$('#showDate').onchange=updateDivision;breed.onchange=calc;$('#superintendent').onchange=()=>$('#otherSuperWrap').classList.toggle('hidden',$('#superintendent').value!=='other');
function records(){let r=JSON.parse(localStorage.getItem('15pts.records')||'[]');return r.map(migrate)} function saveRecords(r){localStorage.setItem('15pts.records',JSON.stringify(r))}
function migrate(r){if(r.schema>=4)return r;if(r.schema===3)return {...r,schema:4,handler:r.handler||'',nohs:!!r.nohs,nohsAwards:r.nohsAwards||[],nohsPoints:r.nohsPoints||0,status:r.status==='champion'?'champion':(r.status||'class')};let awards=[];String(r.award||'').split('_').forEach(a=>{if(['WD','WB','BOW','BOB','BOS','SD','SB'].includes(a)&&!awards.includes(a))awards.push(a)});return {...r,schema:4,handler:'',nohs:false,nohsAwards:[],nohsPoints:0,armband:r.armband||'',state:r.state||'',status:r.track==='GCH'?'champion':'class',awards,original:{points:r.points||0,major:!!r.major,explain:r.explain||'',createdAt:r.id||Date.now()},verification:null,amendments:[]}}
function superInfo(){let k=$('#superintendent').value,row=SUPERS.find(x=>x[0]===k)||SUPERS[0];return {key:k,name:k==='other'?$('#otherSuper').value.trim():row[1],url:row[2]}}
$('#saveBtn').onclick=()=>{let c=calc();if(!$('#dogName').value.trim())return alert('Add the dog’s registered name first.');if(!selectedAwards.size)return alert('Select at least one award earned.');let s=superInfo(),r={schema:4,id:Date.now(),dogId:($('#regNo').value.trim()||crypto.randomUUID()),dog:$('#dogName').value.trim(),reg:$('#regNo').value.trim(),handler:$('#handler').value.trim(),nohs:$('#nohs').checked,nohsAwards:[...selectedNOHS],nohsPoints:[...selectedNOHS].reduce((a,x)=>a+(NOHS_PTS[x]||0),0),armband:$('#armband').value.trim(),sex:$('#sex').value,status:$('#status').value,breed:breed.value,date:$('#showDate').value,show:$('#showName').value.trim(),judge:$('#judge').value.trim(),state:state.value,division:division(),track:isGCH()?'GCH':'CH',awards:[...selectedAwards],superintendent:s,entry:c.entry,original:{points:c.p,major:c.major,explain:c.steps.join(' · '),control:c.control,scheduleVerified:c.verified,createdAt:Date.now()},verification:null,amendments:[]};let rs=records();rs.unshift(r);saveRecords(rs);renderAll();alert(`Saved: ${c.p} point${c.p===1?'':'s'}${c.major?' — major':''}`)};
$('#clearBtn').onclick=()=>{['dogName','regNo','handler','armband','showName','judge','otherSuper'].forEach(id=>$('#'+id).value='');['classDogs','classBitches','champDogs','champBitches','nonRegDogs','nonRegBitches'].forEach(id=>{if($('#'+id))$('#'+id).value=0});selectedAwards.clear();selectedNOHS.clear();$('#nohs').checked=false;renderAwards();renderNOHS();calc()};
function effective(r){if(r.verification)return {points:+r.verification.points,major:!!r.verification.major,verified:true};let last=(r.amendments||[]).at(-1);if(last)return {points:+last.points,major:!!last.major,verified:false};return {points:+r.original.points,major:!!r.original.major,verified:false}}
function renderAll(){let rs=records(),eff=rs.map(r=>({r,e:effective(r)})),ch=eff.filter(x=>x.r.track==='CH').reduce((s,x)=>s+x.e.points,0),chm=eff.filter(x=>x.r.track==='CH'&&x.e.major).length,g=eff.filter(x=>x.r.track==='GCH').reduce((s,x)=>s+x.e.points,0);$('#summary').innerHTML=`<div class="stats"><div class="stat"><strong>${rs.length}</strong><span>RESULTS</span></div><div class="stat"><strong>${ch}</strong><span>CH PTS</span></div><div class="stat"><strong>${chm}</strong><span>CH MAJORS</span></div><div class="stat"><strong>${g}</strong><span>GCH PTS</span></div></div>`;$('#recordList').innerHTML=rs.length?rs.map(recordHTML).join(''):'<div class="empty">No saved results yet.</div>';renderDogs(rs)}
function recordHTML(r){let e=effective(r),diff=r.verification&&(+r.verification.points!==+r.original.points||!!r.verification.major!==!!r.original.major),aw=(r.awards||[]).join(' → '),loc=r.state?`${STATE_NAMES[r.state]} · Division ${r.division}`:`Division ${r.division||'—'}`;return `<div class="record"><div class="recordTop"><div><b>${esc(r.dog)}</b><div class="meta">${r.date||'No date'} · ${esc(r.show||'Show not entered')}<br>${loc} · ${r.track} · ${esc(aw||'Legacy award')} ${r.nohsPoints?`· NOHS ${r.nohsPoints} pts`:''} ${r.armband?`· Armband #${esc(r.armband)}`:''}<br>Handler: ${esc(r.handler||'—')} · Judge: ${esc(r.judge||'—')} · ${esc(r.superintendent?.name||'Superintendent not recorded')}</div></div><span class="pill ${e.major?'major':''}">${e.points} PT${e.points===1?'':'S'}</span></div>${diff?`<div class="discrepancy">Result discrepancy · Original ${r.original.points}${r.original.major?' major':''} → Verified ${r.verification.points}${r.verification.major?' major':''}</div>`:''}<div class="recordActions"><button onclick="details(${r.id})">Details</button><button onclick="verifyRecord(${r.id})">${r.verification?'Edit verification':'Verify results'}</button><button onclick="amendRecord(${r.id})">Amend</button><button class="danger" onclick="del(${r.id})">Delete</button></div></div>`}
function dogKey(r){return r.dogId||r.reg||`${r.dog}|${r.sex}`}
function renderDogs(rs){let map={};rs.forEach(r=>(map[dogKey(r)]??=[]).push(r));$('#dogList').innerHTML=Object.entries(map).length?Object.entries(map).map(([key,a])=>{let d=a[0],ch=a.filter(x=>x.track==='CH'),g=a.filter(x=>x.track==='GCH'),tracked=ch.reduce((s,x)=>s+effective(x).points,0),verified=ch.filter(x=>x.verification).reduce((s,x)=>s+effective(x).points,0),pending=ch.filter(x=>!x.verification).reduce((s,x)=>s+effective(x).points,0),maj=ch.filter(x=>effective(x).major).length,gp=g.reduce((s,x)=>s+effective(x).points,0),gm=g.filter(x=>effective(x).major).length,np=a.reduce((s,x)=>s+(+x.nohsPoints||0),0);return `<div class="dogCard clickable" data-dogkey="${encodeURIComponent(key)}"><span class="dogArrow">›</span><b>${esc(d.dog)}</b><div class="meta">${esc(d.reg||'No registration #')} · ${esc(d.breed)} · ${d.sex==='dog'?'Dog':'Bitch'}</div><div class="progress"><i style="width:${Math.min(100,tracked/15*100)}%"></i></div><div class="meta"><b>CH: ${tracked}/15 · ${maj} major${maj===1?'':'s'}</b><br>Verified CH: ${verified} · Pending CH: ${pending}<br>GCH: ${gp}/25 · ${gm} major${gm===1?'':'s'}${np?`<br>NOHS: ${np} points`:''}<br>${a.length} event${a.length===1?'':'s'}</div></div>`}).join(''):'<div class="empty">Save a result to begin tracking a dog.</div>';$$('[data-dogkey]').forEach(x=>x.onclick=()=>dogDetails(decodeURIComponent(x.dataset.dogkey)))}
window.dogDetails=key=>{let a=records().filter(r=>dogKey(r)===key).sort((x,y)=>(y.date||'').localeCompare(x.date||'')),d=a[0];if(!d)return;let ch=a.filter(x=>x.track==='CH'),g=a.filter(x=>x.track==='GCH'),cp=ch.reduce((s,x)=>s+effective(x).points,0),cm=ch.filter(x=>effective(x).major).length,gp=g.reduce((s,x)=>s+effective(x).points,0),gm=g.filter(x=>effective(x).major).length,np=a.reduce((s,x)=>s+(+x.nohsPoints||0),0);openModal(`<div class="eyebrow">DOG PROFILE</div><h2>${esc(d.dog)}</h2><p>${esc(d.reg||'No registration #')} · ${esc(d.breed)} · ${d.sex==='dog'?'Dog':'Bitch'}</p><h3>Championship</h3><p><b>${cp}/15 points · ${cm} major${cm===1?'':'s'}</b></p><h3>Grand Championship</h3><p><b>${gp}/25 points · ${gm} major${gm===1?'':'s'}</b></p><h3>NOHS</h3><p><b>${np} tracked points</b></p><h3>Show history</h3>${a.map(r=>{let e=effective(r);return `<div class="historyItem" onclick="details(${r.id})"><b>${r.date||'No date'} · ${esc(r.show||'Show')}</b><div class="meta">${esc((r.awards||[]).join(' → '))}${r.nohsAwards?.length?` · ${esc(r.nohsAwards.join(' → '))}`:''}<br>${e.points} ${r.track} point${e.points===1?'':'s'}${e.major?' · MAJOR':''}${r.verification?' · Verified ✓':' · Pending verification'}</div></div>`}).join('')}`)}
function findRec(id){return records().find(r=>r.id===id)} function replaceRec(r){saveRecords(records().map(x=>x.id===r.id?r:x));renderAll()}
window.details=id=>{let r=findRec(id),e=effective(r);openModal(`<div class="eyebrow">SAVED RESULT</div><h2>${esc(r.dog)}</h2><p>${esc(r.show||'Show not entered')} · ${r.date||'No date'}<br>${r.state?esc(STATE_NAMES[r.state]):''} · Division ${r.division||'—'}<br>Handler: ${esc(r.handler||'—')}<br>NOHS: ${r.nohs?'Yes':'No'}${r.nohsAwards?.length?` · ${esc(r.nohsAwards.join(' → '))} · ${r.nohsPoints} pts`:''}<br>Armband: ${esc(r.armband||'—')}<br>Judge: ${esc(r.judge||'—')}<br>Superintendent/Secretary: ${esc(r.superintendent?.name||'—')}</p><h3>Awards</h3><p>${esc((r.awards||[]).join(' → '))}</p><h3>Original 15PTS calculation</h3><p><b>${r.original.points} points${r.original.major?' · MAJOR':''}</b><br>${esc(r.original.explain||'')}</p>${r.amendments?.length?`<h3>Amendments</h3>${r.amendments.map(a=>`<p>${new Date(a.date).toLocaleDateString()}: ${a.points} points${a.major?' · major':''}<br>${esc(a.note||'')}</p>`).join('')}`:''}${r.verification?`<h3>Verified result</h3><p><b>${r.verification.points} points${r.verification.major?' · MAJOR':''}</b><br>${new Date(r.verification.date).toLocaleDateString()} · ${esc(r.verification.note||'No note')}</p>`:''}<h3>Current tracked result</h3><p><b>${e.points} points${e.major?' · MAJOR':''}</b></p>${r.superintendent?.url?`<p><a class="verifyLink" target="_blank" rel="noopener" href="${r.superintendent.url}">Open results source ↗</a></p>`:''}`)};
window.verifyRecord=id=>{let r=findRec(id),cur=r.verification||effective(r);openModal(`<div class="eyebrow">VERIFY RESULTS</div><h2>${esc(r.dog)}</h2><p>Original 15PTS calculation: <b>${r.original.points} points${r.original.major?' · major':''}</b></p>${r.superintendent?.url?`<p><a class="verifyLink" target="_blank" rel="noopener" href="${r.superintendent.url}">Open ${esc(r.superintendent.name)} ↗</a></p>`:''}<label>Verified points<input id="vPoints" type="number" min="0" max="5" value="${cur.points}"></label><label class="check"><input id="vMajor" type="checkbox" ${cur.major?'checked':''}> Verified as a major</label><label>Verification note<textarea id="vNote" placeholder="Optional reason for discrepancy or source detail">${esc(r.verification?.note||'')}</textarea></label><button class="primary modalSave" id="saveVerify">Save verified result</button>`);$('#saveVerify').onclick=()=>{r.verification={points:+$('#vPoints').value,major:$('#vMajor').checked,note:$('#vNote').value.trim(),date:Date.now(),source:r.superintendent?.name||''};replaceRec(r);closeModal()}};
window.amendRecord=id=>{let r=findRec(id),e=effective(r);openModal(`<div class="eyebrow">AMEND TRACKING</div><h2>${esc(r.dog)}</h2><p>The original calculation remains unchanged. This amendment becomes the provisional tracked result unless/until a verified result exists.</p><label>Amended points<input id="aPoints" type="number" min="0" max="5" value="${e.points}"></label><label class="check"><input id="aMajor" type="checkbox" ${e.major?'checked':''}> Major</label><label>Reason / note<textarea id="aNote" placeholder="Example: corrected entry count"></textarea></label><button class="primary modalSave" id="saveAmend">Save amendment</button>`);$('#saveAmend').onclick=()=>{r.amendments=r.amendments||[];r.amendments.push({points:+$('#aPoints').value,major:$('#aMajor').checked,note:$('#aNote').value.trim(),date:Date.now()});replaceRec(r);closeModal()}};
window.del=id=>{if(confirm('Delete this saved result?')){saveRecords(records().filter(r=>r.id!==id));renderAll()}};
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(records(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='15PTS-v4-records.json';a.click();URL.revokeObjectURL(a.href)};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#disclaimerBtn').onclick=()=>openModal(`<div class="eyebrow">15PTS™</div><h2>Disclaimer & Important Information</h2><p>15PTS is an independent exhibitor tool and is not affiliated with, endorsed by, or sponsored by the American Kennel Club.</p><p>Point calculations, championship tracking, competition counts, division assignments, point schedules, and other information provided by 15PTS are intended for informational and personal record-keeping purposes only. Calculations and information are not guaranteed to be accurate, complete, or current.</p><p>Results calculated by 15PTS should not be considered official confirmation of championship points, Grand Championship points, majors, titles, NOHS points, or other American Kennel Club records.</p><p>Exhibitors should verify applicable point schedules, competition counts, show results, championship points, titles, and other information against the appropriate official records.</p><p>© 2026 Ryan Busch. All rights reserved.</p>`);
renderEntry();renderAwards(true);updateDivision();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
